### ISSUE TITLE
Impossible to send the files between PC - Android

### ISSUE THREAD

**Issue by aha999** [genonbeta/TrebleShot-Desktop#28] opened 2019-12-21 20:23 UTC
I tried adding the android device running trebleshot on the PC via IP, on the the pc it found the phone after manually adding the IP, but doesn't send or recieve anything.

The android doesn't find the pc's IP (scanning for devices doesn't do anything. They're on the same wifi network and i turned on the trustZone for my device on the pc after i manually added it and turned on trustzone on android... Nothing.
 
I'd really like trebleshot to work so i tried multiple options as you can see, but this is probably some bugs.

**Comment by velitasali** [comment] 2019-12-21 21:05
This is duplicate of https://github.com/genonbeta/TrebleShot-Desktop/issues/24. Please, use that thread to add new comments.

**Closed by velitasali** 2019-12-21 21:05 UTC
Labels: duplicate
